### ISSUE TITLE
hi!

### ISSUE THREAD

**Issue by aaronbrethorst** [otusweb/iOS-camera-button#1]
<img width="974" alt="screen shot 2016-11-05 at 12 29 17 am" src="https://cloud.githubusercontent.com/assets/2254/20028443/ebc498d8-a2ee-11e6-8288-30adf7224fc4.png">

I just saw that you submitted something to my website. hope you're well!

**Comment by otusweb** [comment]
Hey Aaron, i was actually wondering if you were still working on cocoacontrols. We should catch up, sent you a message via linked in
